[platformio]

[digboards]
build_flags_clnp =
  -D WLED_ENABLE_CLNP
  -D CLNP_DEFAULT_BAUD=19200
  -D CLNP_TX_PIN=2
  -D CLNP_RX_PIN=32
  -D CLNP_EN_PIN=12
  -D CLNP_UART_NUM=2
build_flags_ethernet =
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=4
build_flags_dig_ar =
  -D SR_DMTYPE=1
  -D I2S_SDPIN=-1
  -D I2S_WSPIN=-1
  -D I2S_CKPIN=-1
  -D SR_SQUELCH=10
  -D SR_GAIN=30
build_flags_dig_quad =
  -D WLED_BRAND="\"QuinLED\""
  -D NOWIFISLEEP=false
  -D WLED_DISABLE_BLYNK
  -D RLYPIN=15
  -D BTNPIN=0
  -D IRPIN=-1
  -D PIXEL_COUNTS=30,30,30,30
  -D DATA_PINS=16,3,1,4
  -D ABL_MILLIAMPS_DEFAULT=1250
  -D LED_MILLIAMPS_DEFAULT=10
  -D LED_TYPES=TYPE_WS2805,TYPE_WS2805,TYPE_WS2805,TYPE_WS2805
  -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_RGB
build_flags_dig_uno =
  -D WLED_BRAND="\"QuinLED\""
  -D NOWIFISLEEP=false
  -D WLED_DISABLE_BLYNK
  -D RLYPIN=15
  -D BTNPIN=0
  -D IRPIN=-1
  -D PIXEL_COUNTS=30,30
  -D DATA_PINS=16,3
  -D ABL_MILLIAMPS_DEFAULT=1250
  -D LED_MILLIAMPS_DEFAULT=10
  -D LED_TYPES=TYPE_WS2805,TYPE_WS2805
  -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_RGB
#
# Dig-Uno
#
# All versions have the following base setup:
# 2 LED outputs with 30 LED's
# Button pin on GPIO 0
# Brightness limiter on 1250 mA
# Relay pin on 15 (Q1 on the boards)
#

[env:dig-Uno-V3-ETHON]
extends = env:esp32dev
build_flags = ${common.build_flags} ${esp32.build_flags}
  -D WLED_PRODUCT_NAME="\"Dig-Uno-Ethernet\""
  -D SERVERNAME="\"Dig-Uno-Eth\""
  -D WLED_RELEASE_NAME="\"Dig-Uno-Ethernet\""
  ${digboards.build_flags_dig_uno}
  ${digboards.build_flags_ethernet}
  ${digboards.build_flags_clnp}

[env:dig-Quad-V3-ETHON]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32_idf_V4.build_flags}
  -D WLED_PRODUCT_NAME="\"Dig-Quad-Ethernet\""
  -D SERVERNAME="\"Dig-Quad-Eth\""
  -D WLED_RELEASE_NAME="\"Dig-Quad-Ethernet\""
  ${digboards.build_flags_dig_quad}
  ${digboards.build_flags_ethernet}
  ${digboards.build_flags_clnp}

  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_ALEXA
  ;-D WLED_DISABLE_HUESYNC  ;Provides a an XY to RGB conversion function
  -D WLED_DISABLE_LOXONE
  -D WLED_DISABLE_ADALIGHT
  -D WLED_DISABLE_ESPNOW

  -D WLED_AUTOSEGMENTS

upload_speed = 921600

lib_deps = ${esp32_idf_V4.lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio
